CREATE SEQUENCE public.orders_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE TABLE public.order_status (
	status_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT order_status_name_key UNIQUE (name),
	CONSTRAINT order_status_pkey PRIMARY KEY (status_id)
);


CREATE TABLE public.orders (
	customer_document_number int4 NOT NULL,
	order_id int4 NOT NULL,
	status_id int4 NOT NULL,
	created_at timestamp(6) NOT NULL,
	restaurant_nit int8 NOT NULL,
	CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);


CREATE TABLE public.orders_dishes (
	dish_id int4 NOT NULL,
	order_id int4 NOT NULL,
	price float8 NOT NULL,
	quantity int4 NOT NULL,
	CONSTRAINT orders_dishes_pkey PRIMARY KEY (dish_id, order_id)
);


ALTER TABLE public.orders ADD CONSTRAINT fk1abokg3ghque9pf2ujbxakng FOREIGN KEY (status_id) REFERENCES public.order_status(status_id);
ALTER TABLE public.orders ADD CONSTRAINT fkn0ff16ymxcku69yqhiik610v7 FOREIGN KEY (restaurant_nit) REFERENCES public.restaurants(nit);

ALTER TABLE public.orders_dishes ADD CONSTRAINT fk6on9jka58uq379lr0ai2o7c6w FOREIGN KEY (order_id) REFERENCES public.orders(order_id);
ALTER TABLE public.orders_dishes ADD CONSTRAINT fkblakv5a6hr4l3elowikjv08ot FOREIGN KEY (dish_id) REFERENCES public.dishes(id);