CREATE TABLE public.order_otps (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(255) NULL,
	created_at timestamp(6) NULL,
	expires_at timestamp(6) NULL,
	order_id varchar(255) NULL,
	used bool NULL,
	CONSTRAINT order_otps_pkey PRIMARY KEY (id)
);